apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: mysql-manager-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - mysql-manager-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - mysql.kdichalas.net
  resources:
  - '*'
  - mysql
  verbs:
  - get
  - list
  - patch
  - update
  - watch
